export const PHASES={ATTACK:'ATTACK',DEFENSE:'DEFENSE',RESULT:'RESULT',GAME_OVER:'GAME_OVER'};
export const isPrime=n=>{if(n<2)return false;if(n===2)return true;if(n%2===0)return false;for(let i=3;i<=Math.sqrt(n);i+=2)if(n%i===0)return false;return true};
export const shuffle=a=>{const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
export const makeDeck=owner=>shuffle(Array.from({length:10},(_,i)=>['A','B','C'].map(type=>({id:`${owner}-${i+1}-${type}-${crypto.randomUUID()}`,number:i+1,type,zone:'deck'}))).flat());
export const makePlayer=(name,i)=>({id:`p${i}`,name,deck:makeDeck(i),hand:[],graveyard:[],lifeZone:Array.from({length:13},(_,n)=>({id:`life-${i}-${n+1}`,number:n+1,type:'L',zone:'life'})),hasPassDrawBonus:false});
export const draw=(p,n=1)=>{for(let i=0;i<n&&p.deck.length;i++){const c=p.deck.shift();c.zone='hand';p.hand.push(c)}};
export const numberFrom=cards=>Number(cards.map(c=>c.number).join(''));
export const sumNumbers=cards=>cards.reduce((sum,c)=>sum+c.number,0);
export const getGroup=c=>c.number<=3?'LOW':c.number<=6?'MIDDLE':'HIGH';
export function validateAttack(cards){if(!cards.length)return{isValid:false,message:'攻撃カードを1枚以上選んでください。'};if(cards.length>3)return{isValid:false,message:'攻撃に使えるカードは最大3枚です。'};const counts=cards.reduce((a,c)=>(a[getGroup(c)]++,a),{LOW:0,MIDDLE:0,HIGH:0});if(counts.HIGH>1)return{isValid:false,message:'7〜13のカードは1回の攻撃につき1枚までです。'};if(counts.MIDDLE>1)return{isValid:false,message:'4〜6のカードは1回の攻撃につき1枚までです。'};const n=sumNumbers(cards);if(!isPrime(n))return{isValid:false,message:`合計 ${n} は素数ではありません。`};return{isValid:true,message:`合計 ${n} で攻撃可能です。`,number:n}}
export const createGame=(names)=>{const players=names.map(makePlayer);players.forEach(p=>draw(p,5));return{turn:1,phase:PHASES.ATTACK,active:Math.random()<.5?0:1,players,external:shuffle([11,11,11,12,12,12,13,13,13]),externalGrave:[],selected:[],attack:null,defense:null,logs:['ゲームを開始しました。'],winner:null,lastResult:null}};
export function publicLog(g,m){g.logs.push(m);if(g.logs.length>80)g.logs.shift()}
export function startTurn(g){const p=g.players[g.active];draw(p,1);publicLog(g,`${p.name}が通常ドローを1枚行いました。`);g.phase=PHASES.ATTACK;g.selected=[]}
export function passTurn(g){const p=g.players[g.active];p.hasPassDrawBonus=true;publicLog(g,`${p.name}は攻撃をパスしました。次回ターンに選択ドローを行います。`);endTurn(g,true)}
export function beginAttack(g,cards){const v=validateAttack(cards);if(!v.isValid)return v;const aCount=cards.filter(c=>c.type==='A').length,bCount=cards.filter(c=>c.type==='B').length,cCount=cards.filter(c=>c.type==='C').length;g.attack={cards:[...cards],base:v.number,value:v.number+bCount,aCount,bCount,cCount};g.phase=PHASES.DEFENSE;publicLog(g,`${g.players[g.active].name}が素数 ${v.number} で攻撃しました。`);return v}
export function resolveDefense(g,method,cards=[]){const defender=g.players[1-g.active];let defense=0,externalCard=null;if(method==='hand'){defense=numberFrom(cards);g.defense={method,cards:[...cards],value:defense}}else{externalCard=g.external.shift();defense=Math.max(0,(externalCard||0)-g.attack.cCount*2);g.defense={method,cards:[],externalCard,value:defense}}const damage=Math.max(0,g.attack.value-defense);const moved=defender.lifeZone.filter(c=>c.number<=damage);defender.lifeZone=defender.lifeZone.filter(c=>c.number>damage);moved.forEach(c=>c.zone='hand');defender.hand.push(...moved);const attacker=g.players[g.active];g.attack.cards.forEach(c=>{attacker.hand=attacker.hand.filter(x=>x.id!==c.id);c.zone='grave';attacker.graveyard.push(c)});if(method==='hand')cards.forEach(c=>{defender.hand=defender.hand.filter(x=>x.id!==c.id);c.zone='grave';defender.graveyard.push(c)});else if(externalCard!=null)g.externalGrave.push(externalCard);draw(attacker,g.attack.aCount);const result={attack:g.attack.value,base:g.attack.base,defense,damage,moved:moved.map(c=>c.number),drawn:g.attack.aCount,method};g.lastResult=result;publicLog(g,`攻撃 ${result.attack}、防御 ${defense}、ダメージ ${damage}。ライフカードを${moved.length}枚移動しました。`);if(!defender.lifeZone.length){g.winner=g.active;g.phase=PHASES.GAME_OVER}else g.phase=PHASES.RESULT;return result}
export function endTurn(g,fromPass=false){if(!fromPass)g.players[g.active].hasPassDrawBonus=g.players[g.active].hasPassDrawBonus;g.active=1-g.active;g.turn++;g.selected=[];g.attack=null;g.defense=null;g.lastResult=null;startTurn(g);saveGame(g)}
export function applyPassDraw(g,cardId){const p=g.players[g.active];const choices=p.deck.slice(0,2);const chosen=choices.find(c=>c.id===cardId);if(!chosen)return;const rejected=choices.find(c=>c.id!==cardId);p.deck=p.deck.slice(choices.length);chosen.zone='hand';p.hand.push(chosen);if(rejected)p.deck.push(rejected);p.hasPassDrawBonus=false;publicLog(g,`${p.name}は選択ドローで1枚を手札に加え、残りを山札の一番下へ送りました。`)}
export const saveGame=g=>localStorage.setItem('prime-duel-save',JSON.stringify(g));
export const loadGame=()=>{try{return JSON.parse(localStorage.getItem('prime-duel-save'))}catch{return null}};
export const clearSave=()=>localStorage.removeItem('prime-duel-save');
