import{joinRoom}from'https://esm.run/@trystero-p2p/mqtt@0.25.3';
import{PHASES,createGame,startTurn,beginAttack,resolveDefense,endTurn,passTurn,applyPassDraw,validateAttack,clearSave}from'./game.js';
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');let game=null,screen='title',selected=[],order=[],peerRoom=null,stateAction=null,helloAction=null,noticeAction=null,myIndex=null,roomCode='',myName='',myRole='player',isHost=false,joinTimer=null,opponentPeerId=null;const peerRoles=new Map();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cardHtml=(c,{selected=false,hidden=false,life=false}={})=>`<button class="card ${selected?'selected':''} ${hidden?'hidden':''} ${life?'life-card':''}" data-card="${c.id}" ${hidden?'disabled':''}><span class="num">${c.number}</span><span class="type">${c.type}</span><span class="effect">${c.type==='A'?'使用時: 1枚ドロー':c.type==='B'?'攻撃値 +1':c.type==='C'?'外部防御 -2':c.type==='L'?'効果なし':' '}</span></button>`;
function title(){app.innerHTML=`<section class="hero"><div class="hero-card"><p class="eyebrow">ONLINE PRIME CARD GAME · MQTT v9</p><h1>PRIME<br>DUEL</h1><p class="sub">ルームコードでつながる、2人用オンラインカードゲーム。<br>対戦への参加だけでなく、進行中のゲームも観戦できます。</p><div class="form-row"><input class="input" id="name" maxlength="16" value="プレイヤー" aria-label="プレイヤー名"><input class="input room-input" id="room" maxlength="6" inputmode="text" autocapitalize="characters" autocomplete="off" autocorrect="off" spellcheck="false" enterkeyhint="go" placeholder="ルームコード" aria-label="ルームコード"></div><div class="footer-actions"><button class="btn primary" id="create">ルームを作る</button><button class="btn gold" id="join">ルームに参加</button><button class="btn" id="spectate">観戦する</button><button class="btn" id="rules">ルール</button></div><p id="lobby-error" class="error" hidden></p></div></section>`;document.querySelector('#create').onclick=()=>connect('create');document.querySelector('#join').onclick=()=>connect('join');document.querySelector('#spectate').onclick=()=>connect('spectate');const roomInput=document.querySelector('#room');const sanitizeRoom=()=>roomInput.value=roomInput.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6);roomInput.addEventListener('blur',sanitizeRoom);roomInput.addEventListener('compositionend',sanitizeRoom);document.querySelector('#rules').onclick=rulesModal}
function connect(mode){myName=document.querySelector('#name').value.trim()||(mode==='spectate'?'観戦者':'プレイヤー');const requested=document.querySelector('#room').value.trim().toUpperCase();if(mode!=='create'&&requested.length!==6)return lobbyError('6文字のルームコードを入力してください。');isHost=mode==='create';myRole=isHost?'host':mode==='spectate'?'spectator':'player';myIndex=isHost?0:mode==='join'?1:null;roomCode=isHost?makeRoomCode():requested;try{peerRoom=joinRoom({appId:'prime-duel-online-mqtt-v3',relayConfig:{redundancy:3,warnOnRelayFailure:false}},roomCode,{onJoinError:()=>lobbyError('相手との直接接続を確立できませんでした。別の回線でもお試しください。')});stateAction=peerRoom.makeAction('game-state');helloAction=peerRoom.makeAction('player-hello');noticeAction=peerRoom.makeAction('room-notice');stateAction.onMessage=state=>receiveState(state);helloAction.onMessage=(player,{peerId})=>receiveHello(player,peerId);noticeAction.onMessage=notice=>{if(notice.type==='room-full')connectionModal('このルームの対戦枠は満員です。「観戦する」から入り直してください。')};peerRoom.onPeerJoin=peerId=>{clearTimeout(joinTimer);helloAction.send({name:myName,index:myIndex,role:myRole},{target:peerId});if(!isHost)waitingRoom(myRole==='spectator'?'ルームと接続しました。盤面を受信しています…':'ホストと接続しました。ゲームを準備しています…')};peerRoom.onPeerLeave=peerId=>{const role=peerRoles.get(peerId);peerRoles.delete(peerId);if(peerId===opponentPeerId||role==='host'||(myRole==='spectator'&&role==='player'))connectionModal('対戦プレイヤーがルームから退出しました。')};waitingRoom(isHost?'MQTTルームを作成しました。相手の参加を待っています':myRole==='spectator'?'観戦するルームを探しています…':'MQTTルームを探しています…');if(!isHost)joinTimer=setTimeout(()=>{if(!game)connectionModal('ルームが見つかりません。コードを確認し、両方の端末でMQTT v8と表示されているか確認してください。')},35000)}catch(error){lobbyError('MQTT通信の準備に失敗しました。ページを再読み込みしてください。')}}
function makeRoomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=crypto.getRandomValues(new Uint8Array(6));return Array.from(bytes,n=>chars[n%chars.length]).join('')}
function receiveHello(player,peerId){clearTimeout(joinTimer);peerRoles.set(peerId,player.role||'player');if(!isHost)return;if(player.role==='spectator'){if(game)stateAction.send(game,{target:peerId});return}if(player.role!=='player')return;if(game||opponentPeerId){noticeAction.send({type:'room-full'},{target:peerId});return}opponentPeerId=peerId;game=createGame([myName,String(player.name||'プレイヤー').slice(0,16)]);startTurn(game);screen='game';render();sync()}
function receiveState(state){if(!state?.players)return;clearTimeout(joinTimer);game=state;screen='game';modalRoot.innerHTML='';selected=[];order=[];render();if(operatorIndex()===myIndex&&game.players[myIndex].hasPassDrawBonus)passDrawModal()}
function sync(){if(!stateAction||!game||!peerRoom)return;const peers=Object.keys(peerRoom.getPeers());Promise.all(peers.map(peerId=>stateAction.send(game,{target:peerId}))).catch(()=>connectionModal('対戦データを送信できませんでした。'))}
function lobbyError(message){const el=document.querySelector('#lobby-error');if(el){el.hidden=false;el.textContent=message}else connectionModal(message)}
function waitingRoom(message='相手の参加を待っています'){app.innerHTML=`<section class="hero"><div class="hero-card"><p class="eyebrow">ROOM CREATED</p><h2>${esc(message)}</h2><div class="prime-display"><div><div class="prime-number">${roomCode}</div><div class="equation">このコードを相手に伝えてください</div></div></div><button class="btn" id="copy">コードをコピー</button></div></section>`;document.querySelector('#copy')?.addEventListener('click',()=>navigator.clipboard.writeText(roomCode))}
function connectionModal(message){clearTimeout(joinTimer);modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><p class="eyebrow">CONNECTION</p><h2>${esc(message)}</h2><button class="btn primary" id="back-title">タイトルへ</button></div></div>`;document.querySelector('#back-title').onclick=()=>{peerRoom?.leave();location.reload()}}
function rulesModal(){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><p class="eyebrow">HOW TO PLAY</p><h2>3枚までの合計で素数攻撃</h2><div class="rule-grid"><div><b>攻撃</b><p>手札から1〜3枚を選び、数字の合計が素数なら攻撃。7〜13帯と4〜6帯は各1枚まで。</p></div><div><b>防御</b><p>手札1〜2枚の数字の合計、または共有の外部カードで防御。差分以下のライフを手札へ。</p></div><div><b>カード効果</b><p>Aはドロー、Bは攻撃+1、Cは外部防御-2。</p></div><div><b>パス</b><p>いつでもパス可能。次の自分のターンに山札上2枚から1枚を選ぶ。</p></div></div><button class="btn primary" id="close-modal">閉じる</button></div></div>`;document.querySelector('#close-modal').onclick=()=>modalRoot.innerHTML=''}
function handoff(_message,after){after?.();sync()}
const operatorIndex=()=>game.phase===PHASES.DEFENSE?1-game.active:game.active;
function playerPanel(p,i){const active=i===operatorIndex(),visible=myRole==='spectator'||i===myIndex;return `<section class="player ${active?'active':''}"><h2>${esc(p.name)} ${active?'<span class="badge">操作中</span>':''}</h2><div class="stats"><div class="stat"><strong>${p.deck.length}</strong><span>山札</span></div><div class="stat"><strong>${p.hand.length}</strong><span>手札</span></div><div class="stat"><strong>${p.graveyard.length}</strong><span>墓地</span></div><div class="stat"><strong>${p.lifeZone.length}</strong><span>残りライフ</span></div></div><div class="life">${p.lifeZone.map(c=>`<i>${c.number}</i>`).join('')}</div>${visible?`<h3>${myRole==='spectator'?'公開手札':'あなたの手札'}</h3><div class="cards">${p.hand.map(c=>cardHtml(c,{selected:selected.includes(c.id)})).join('')||'<p class="sub">手札がありません</p>'}</div>`:`<h3>相手の手札</h3><div class="cards">${p.hand.map(c=>cardHtml(c,{hidden:true})).join('')}</div>`}</section>`}
function render(){if(!game)return title();const a=game.players[operatorIndex()],validation=game.phase===PHASES.ATTACK?validateAttack(order):null;app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">PRIME <b>DUEL</b></div><div><span class="badge">ROOM ${roomCode}</span> ${myRole==='spectator'?'<span class="badge">観戦中</span>':''}<span class="badge turn">TURN ${game.turn}</span> <span class="badge">${phaseName()}</span> <span class="badge">外部ゾーン ${game.external.length}</span></div><button class="btn" id="rules">ルール</button></header><div class="grid">${playerPanel(game.players[0],0)}<section class="panel board-center"><p class="eyebrow">${esc(a.name)}'S ACTION</p><h2>${instruction()}</h2><div class="prime-display">${centerDisplay(validation)}</div>${actionControls(validation)}<h3>ゲームログ</h3><div class="log">${game.logs.map(x=>`<div>${esc(x)}</div>`).join('')}</div><div class="footer-actions"><button class="btn danger" id="restart">ルーム退出</button></div></section>${playerPanel(game.players[1],1)}</div></div>`;bind();if(game.phase===PHASES.GAME_OVER)gameOver()}
const phaseName=()=>game.phase===PHASES.ATTACK?'攻撃カード選択':game.phase===PHASES.DEFENSE?'防御方法選択':game.phase===PHASES.RESULT?'ターン結果':'勝敗決定';
const instruction=()=>game.phase===PHASES.ATTACK?'1〜3枚を選び、数字の合計で素数を作る':game.phase===PHASES.DEFENSE?'手札か外部ゾーンで防御する':game.phase===PHASES.RESULT?'攻防の結果':'ゲーム終了';
function centerDisplay(v){if(game.phase===PHASES.ATTACK){const total=order.reduce((sum,c)=>sum+c.number,0),formula=order.length?`${order.map(c=>c.number).join(' + ')} = ${total}`:'—';return`<div><div class="prime-number">${total||'—'}</div><div class="equation">${formula}</div><div class="equation">${v?.message||'カードを1〜3枚選択してください'}</div></div>`}if(game.phase===PHASES.DEFENSE)return`<div><div class="prime-number">${game.attack.value}</div><div class="equation">基本 ${game.attack.base} + B効果 ${game.attack.bCount}</div></div>`;if(game.lastResult)return`<div><div class="prime-number">${game.lastResult.damage}</div><div class="equation">攻撃 ${game.lastResult.attack} − 防御 ${game.lastResult.defense}</div></div>`;return''}
function actionControls(v){if(myRole==='spectator')return`<p class="hint">観戦中です。${esc(game.players[operatorIndex()].name)}の操作を表示しています。</p>`;if(operatorIndex()!==myIndex)return`<p class="hint">${esc(game.players[operatorIndex()].name)}の操作を待っています…</p>`;if(game.phase===PHASES.ATTACK)return`<div class="actions"><button class="btn primary" id="attack" ${!v?.isValid?'disabled':''}>攻撃確定</button><button class="btn gold" id="pass">パス</button></div>${v&&!v.isValid&&order.length?`<p class="error">${esc(v.message)}</p>`:''}`;if(game.phase===PHASES.DEFENSE)return`<div class="actions"><button class="btn primary" id="defend-hand" ${selected.length<1||selected.length>2?'disabled':''}>手札で防御</button><button class="btn gold" id="defend-ext" ${!game.external.length?'disabled':''}>外部ゾーン</button></div><p class="hint">手札防御は1〜2枚の数字を合計します。素数である必要はありません。外部ゾーンは上の1枚を使用します。</p>`;if(game.phase===PHASES.RESULT)return`<div class="actions"><button class="btn primary" id="next">次のターンへ</button></div><p class="hint">ライフ移動: ${game.lastResult.moved.join(', ')||'なし'} ／ Aドロー: ${game.lastResult.drawn}枚</p>`;return''}
function bind(){document.querySelector('#rules').onclick=rulesModal;document.querySelector('#restart').onclick=()=>{if(confirm('現在のルームから退出しますか？'))location.reload()};document.querySelector('#save')?.remove();document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>toggleCard(el.dataset.card));document.querySelector('#attack')?.addEventListener('click',()=>{beginAttack(game,order);selected=[];order=[];handoff('',render)});document.querySelector('#pass')?.addEventListener('click',()=>{passTurn(game);selected=[];order=[];handoff('',render)});document.querySelector('#defend-hand')?.addEventListener('click',()=>{const cards=game.players[1-game.active].hand.filter(c=>selected.includes(c.id));resolveDefense(game,'hand',cards);selected=[];render();sync()});document.querySelector('#defend-ext')?.addEventListener('click',()=>{resolveDefense(game,'external');selected=[];render();sync()});document.querySelector('#next')?.addEventListener('click',()=>{endTurn(game);handoff('',render)})}
function toggleCard(id){if(operatorIndex()!==myIndex)return;const p=game.players[operatorIndex()];if(game.phase===PHASES.ATTACK){if(selected.includes(id)){selected=selected.filter(x=>x!==id);order=order.filter(c=>c.id!==id)}else{const c=p.hand.find(c=>c.id===id);const tentative=[...order,c];const band=validateBandOnly(tentative);if(!band.ok){flash(band.message);return}if(selected.length>=3)return flash('攻撃カードは最大3枚です。');selected.push(id);order.push(c)}}else if(game.phase===PHASES.DEFENSE){if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<2)selected.push(id);else return flash('防御カードは最大2枚です。')}render()}
function validateBandOnly(cards){const high=cards.filter(c=>c.number>=7).length,mid=cards.filter(c=>c.number>=4&&c.number<=6).length;return high>1?{ok:false,message:'7〜13のカードは1枚までです。'}:mid>1?{ok:false,message:'4〜6のカードは1枚までです。'}:{ok:true}}
function flash(m){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><p class="error">${esc(m)}</p><button class="btn primary" id="ok">確認</button></div></div>`;document.querySelector('#ok').onclick=()=>modalRoot.innerHTML=''}
function passDrawModal(){const p=game.players[game.active],choices=p.deck.slice(0,2);if(!choices.length){p.hasPassDrawBonus=false;render();sync();return}if(choices.length===1){applyPassDraw(game,choices[0].id);render();sync();return}modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><p class="eyebrow">PASS DRAW BONUS</p><h2>山札の上から1枚を選ぶ</h2><p class="sub">選ばなかったカードは山札の一番下へ移動します。</p><div class="choice-cards">${choices.map(c=>cardHtml(c)).join('')}</div></div></div>`;modalRoot.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{applyPassDraw(game,el.dataset.card);modalRoot.innerHTML='';render();sync()})}
function gameOver(){clearSave();const w=game.players[game.winner];modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><p class="eyebrow">GAME OVER</p><h1>${esc(w.name)}<br>WIN</h1><p class="sub">相手のライフゾーンをすべて攻略しました。</p><button class="btn primary" id="back-title">タイトルへ</button></div></div>`;document.querySelector('#back-title').onclick=()=>{game=null;modalRoot.innerHTML='';title()}}
title();
window.addEventListener('beforeunload',()=>peerRoom?.leave());
